name: sellamak_lk
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.0.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.3.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#000000" # Modern black status bar
  fullscreen: true
